### ISSUE TITLE
Extension Issue? 

### ISSUE THREAD

**Issue by alvinthechipmunk** [fwdcp/CompCtrl#3]
I've placed the necessary files into the sourcemod folders but for some reason the plugin doesn't load correctly. I'm not sure what I could be doing incorrectly.

29 <Failed> "CompCtrl Match Management" (0.3.0) by Forward Command Post
Load error: Required extension "CompCtrl" file("compctrl.ext") not running

**Comment by mr64bit** [comment]
Make sure that compctrl.ext.2.tf2.so or compctrl.ext.2.tf2.dll are in your addons/sourcemod/extensions folder. (.so for a linux machine, .dll for windows)

**Comment by alvinthechipmunk** [comment]
I'm using a windows server, I've tried replacing the dll multiple times to no avail.

**Comment by mr64bit** [comment]
You've restarted the server?
See if CompCtrl is listed in `meta list` and `sm exts list`.

**Comment by alvinthechipmunk** [comment]
It's not in meta list

In exts list it says: 
[15] <FAILED> file "compctrl.ext.so": /servers/epicdemics/tf/addons/sourcemod/extensions/compctrl.ext.so: cannot open shared object file: No such file or directory

Would possibly having some leftovers from the Linux BINARY be affecting it?

**Comment by mr64bit** [comment]
This looks like a linux server, try putting the .so file in extensions.

**Comment by alvinthechipmunk** [comment]
Interesting. I could've sworn they said it was a windows server. Thanks a lot, sorry for the bother.

**Comment by AndKenneth** [comment]
@alvinthechipmunk generally you can put both there and it will just ignore the one it can't load.

**Comment by alvinthechipmunk** [comment]
Nice to know. Thanks.
