### ISSUE TITLE
The plugin is not loading in my server. 

### ISSUE THREAD

**Issue by Mer3k** [fwdcp/CompCtrl#4]
Hello,
          When I attempt to run your plugin on my server, I get the error "Load error: Required extension "CompCtrl" file("compctrl.ext") not running". I've installed both versions of the plugin (Linux and Windows) to no avail. The extension did not appear when checking my "meta list" or after using the "sm exts list". I'm not sure what I did wrong.

**Comment by thesupremecommander** [comment]
Can you verify that there are CompCtrl extensions in the SourceMod extensions directory? Also, what happens if you attempt to load the extension manually using `sm exts load compctrl`?

**Comment by Mer3k** [comment]
] rcon sm exts load compctrl
[SM] Loaded extension compctrl.ext.so successfully.

And yes, I have both the compctrl.ext.2.tf2.so and the compctrl.ext.2.tf2.dll extension files in my tf/addons/sourcemod/extensions folder.

Even though it says that the extension loaded successfully when I try:
] rcon sm plugins load compctrl-matches
[SM] Plugin compctrl-matches.smx failed to load: Required extension "CompCtrl" file("compctrl.ext") not running.
I still get the same error.
